package sample.mapper;

import java.util.List;
import sample.model.ItemInfo;
import sample.model.ItemInfoExample;
import sample.model.ItemInfoKey;

public interface ItemInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.item_info
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int deleteByPrimaryKey(ItemInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.item_info
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int insert(ItemInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.item_info
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int insertSelective(ItemInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.item_info
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	List<ItemInfo> selectByExample(ItemInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.item_info
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	ItemInfo selectByPrimaryKey(ItemInfoKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.item_info
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int updateByPrimaryKeySelective(ItemInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.item_info
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int updateByPrimaryKey(ItemInfo record);

	/**
	 * 「MyBatis Generator」で自動生成されるMapperクラスとは別に、独自に定義したメソッドを提供するクラスです。
	 * 
	 * @author f-konashi
	 * 
	 */

	/**
	 * テーブルデータを全件取得する
	 * 
	 * @param
	 * @return
	 */
	List<ItemInfo> getAll();

}