package sample.mapper;

import java.util.List;
import sample.model.ItemInCart;
import sample.model.ItemInCartExample;
import sample.model.ItemInCartKey;
import sample.model.ItemInfoEx;

public interface ItemInCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_in_cart
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    int deleteByPrimaryKey(ItemInCartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_in_cart
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    int insert(ItemInCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_in_cart
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    int insertSelective(ItemInCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_in_cart
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    List<ItemInCart> selectByExample(ItemInCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_in_cart
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    ItemInCart selectByPrimaryKey(ItemInCartKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_in_cart
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    int updateByPrimaryKeySelective(ItemInCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.item_in_cart
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    int updateByPrimaryKey(ItemInCart record);
    
	/**
	 * DBに登録する。
	 * 
	 *　@param 
	 *	Integer userId: 会員管理番号 
	 *	Integer itemId: 商品管理番号
	 *	Integer itemCount:　商品個数
	 *
	 * @return 
	 * 	int
	 * 	・買い物かごに追加した商品数をリターンする。
	 * 	・null値がリターンされることはない。
	 */
    int insertOne(ItemInCart record);
    
    /**
     * 
     * @param userId: 会員管理番号
     * @return List<ItemInfo>:　買い物かごに入っている商品リスト
     */
    List<ItemInfoEx> selectItemInCart(Integer userId);
    
    /**
     * 
     * @param loginId: 会員管理番号
     * @return int:　削除されたレコード件数
     */
    int deleteItemByUserId(Integer userId);
    
    /**
     * 
     * @param cartId: 買い物かご管理番号
     * @return int:　削除されたレコード件数
     */
    int deleteItemInCartByCartId(Integer cartId);
}