package sample.mapper;

import java.util.List;
import sample.model.Testtable;
import sample.model.TesttableExample;
import sample.model.TesttableKey;

public interface TesttableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testtable
     *
     * @mbggenerated Mon Nov 30 18:16:39 JST 2015
     */
    int deleteByPrimaryKey(TesttableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testtable
     *
     * @mbggenerated Mon Nov 30 18:16:39 JST 2015
     */
    int insert(Testtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testtable
     *
     * @mbggenerated Mon Nov 30 18:16:39 JST 2015
     */
    int insertSelective(Testtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testtable
     *
     * @mbggenerated Mon Nov 30 18:16:39 JST 2015
     */
    List<Testtable> selectByExample(TesttableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testtable
     *
     * @mbggenerated Mon Nov 30 18:16:39 JST 2015
     */
    Testtable selectByPrimaryKey(TesttableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testtable
     *
     * @mbggenerated Mon Nov 30 18:16:39 JST 2015
     */
    int updateByPrimaryKeySelective(Testtable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.testtable
     *
     * @mbggenerated Mon Nov 30 18:16:39 JST 2015
     */
    int updateByPrimaryKey(Testtable record);
    
    /**
     * 全件データを取得する
     */
    List<Testtable> getTesttableAll();
}