package sample.mapper;

import java.util.List;
import sample.model.UserAuthority;
import sample.model.UserAuthorityExample;
import sample.model.UserAuthorityKey;

public interface UserAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_authority
     *
     * @mbggenerated Thu Dec 03 16:16:47 JST 2015
     */
    int deleteByPrimaryKey(UserAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_authority
     *
     * @mbggenerated Thu Dec 03 16:16:47 JST 2015
     */
    int insert(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_authority
     *
     * @mbggenerated Thu Dec 03 16:16:47 JST 2015
     */
    int insertSelective(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_authority
     *
     * @mbggenerated Thu Dec 03 16:16:47 JST 2015
     */
    List<UserAuthority> selectByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_authority
     *
     * @mbggenerated Thu Dec 03 16:16:47 JST 2015
     */
    UserAuthority selectByPrimaryKey(UserAuthorityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_authority
     *
     * @mbggenerated Thu Dec 03 16:16:47 JST 2015
     */
    int updateByPrimaryKeySelective(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_authority
     *
     * @mbggenerated Thu Dec 03 16:16:47 JST 2015
     */
    int updateByPrimaryKey(UserAuthority record);
}