package sample.mapper;

import java.util.List;
import sample.model.UserInfo;
import sample.model.UserInfoExample;
import sample.model.UserInfoKey;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    int deleteByPrimaryKey(UserInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    UserInfo selectByPrimaryKey(UserInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_info
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    int updateByPrimaryKey(UserInfo record);
    
	/**
	 * テーブルデータを全件取得する。
	 * 
	 * @param
	 * @return
	 */
	List<UserInfo> getAll();

	/**
	 * データを１件挿入する。
	 * 
	 * @param
	 * @return
	 */
	int insertOne(UserInfo record);

	/**
	 * ログインIDからユーザー情報を取得する。
	 * 
	 * @param
	 * @return
	 */
	UserInfo selectByLoginId(String loginId);
}