package sample.mapper;

import java.util.List;
import sample.model.UserAuthority;
import sample.model.UserAuthorityExample;
import sample.model.UserAuthorityKey;

public interface UserAuthorityMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.user_authority
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int deleteByPrimaryKey(UserAuthorityKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.user_authority
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int insert(UserAuthority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.user_authority
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int insertSelective(UserAuthority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.user_authority
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	List<UserAuthority> selectByExample(UserAuthorityExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.user_authority
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	UserAuthority selectByPrimaryKey(UserAuthorityKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.user_authority
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int updateByPrimaryKeySelective(UserAuthority record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table public.user_authority
	 *
	 * @mbggenerated Fri Dec 04 14:21:06 JST 2015
	 */
	int updateByPrimaryKey(UserAuthority record);

	/**
	 * 「MyBatis Generator」で自動生成されるMapperクラスとは別に、独自に定義したメソッドを提供するクラスです。
	 * 
	 * @author f-konashi
	 * 
	 */

	/**
	 * ログインIDからユーザー情報を検索する。
	 * 
	 * @param
	 * @return
	 */
	List<UserAuthority> selectByUserId(Integer userId);

}