package sample.model;

import java.util.Date;

public class BuyingHistory extends BuyingHistoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.buying_history.user_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.buying_history.buying_date
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Date buyingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.buying_history.payment
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private String payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.buying_history.delivery
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private String delivery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.buying_history.postage
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Integer postage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.buying_history.total_price
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Integer totalPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.buying_history.user_id
     *
     * @return the value of public.buying_history.user_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.buying_history.user_id
     *
     * @param userId the value for public.buying_history.user_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.buying_history.buying_date
     *
     * @return the value of public.buying_history.buying_date
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Date getBuyingDate() {
        return buyingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.buying_history.buying_date
     *
     * @param buyingDate the value for public.buying_history.buying_date
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setBuyingDate(Date buyingDate) {
        this.buyingDate = buyingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.buying_history.payment
     *
     * @return the value of public.buying_history.payment
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.buying_history.payment
     *
     * @param payment the value for public.buying_history.payment
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setPayment(String payment) {
        this.payment = payment == null ? null : payment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.buying_history.delivery
     *
     * @return the value of public.buying_history.delivery
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public String getDelivery() {
        return delivery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.buying_history.delivery
     *
     * @param delivery the value for public.buying_history.delivery
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setDelivery(String delivery) {
        this.delivery = delivery == null ? null : delivery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.buying_history.postage
     *
     * @return the value of public.buying_history.postage
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Integer getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.buying_history.postage
     *
     * @param postage the value for public.buying_history.postage
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setPostage(Integer postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.buying_history.total_price
     *
     * @return the value of public.buying_history.total_price
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Integer getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.buying_history.total_price
     *
     * @param totalPrice the value for public.buying_history.total_price
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }
}