package sample.model;

public class BuyingHistoryKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.buying_history.buying_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Integer buyingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.buying_history.buying_id
     *
     * @return the value of public.buying_history.buying_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Integer getBuyingId() {
        return buyingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.buying_history.buying_id
     *
     * @param buyingId the value for public.buying_history.buying_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setBuyingId(Integer buyingId) {
        this.buyingId = buyingId;
    }
}