package sample.model;

public class ItemInCart extends ItemInCartKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_in_cart.user_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_in_cart.item_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_in_cart.item_count
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Integer itemCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_in_cart.user_id
     *
     * @return the value of public.item_in_cart.user_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_in_cart.user_id
     *
     * @param userId the value for public.item_in_cart.user_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_in_cart.item_id
     *
     * @return the value of public.item_in_cart.item_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_in_cart.item_id
     *
     * @param itemId the value for public.item_in_cart.item_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_in_cart.item_count
     *
     * @return the value of public.item_in_cart.item_count
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Integer getItemCount() {
        return itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_in_cart.item_count
     *
     * @param itemCount the value for public.item_in_cart.item_count
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }
}