package sample.model;

public class ItemInfo extends ItemInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_info.name
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_info.price
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_info.postage
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    private String postage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_info.stock
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    private String stock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_info.name
     *
     * @return the value of public.item_info.name
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_info.name
     *
     * @param name the value for public.item_info.name
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_info.price
     *
     * @return the value of public.item_info.price
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_info.price
     *
     * @param price the value for public.item_info.price
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_info.postage
     *
     * @return the value of public.item_info.postage
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    public String getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_info.postage
     *
     * @param postage the value for public.item_info.postage
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    public void setPostage(String postage) {
        this.postage = postage == null ? null : postage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_info.stock
     *
     * @return the value of public.item_info.stock
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_info.stock
     *
     * @param stock the value for public.item_info.stock
     *
     * @mbggenerated Wed Dec 02 16:57:06 JST 2015
     */
    public void setStock(String stock) {
        this.stock = stock == null ? null : stock.trim();
    }
}