package sample.model;

public class ItemInCartKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_in_cart.cart_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Integer cartId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_in_cart.cart_id
     *
     * @return the value of public.item_in_cart.cart_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Integer getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_in_cart.cart_id
     *
     * @param cartId the value for public.item_in_cart.cart_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }
}