package sample.model;

public class ItemInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.item_info.item_id
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.item_info.item_id
     *
     * @return the value of public.item_info.item_id
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.item_info.item_id
     *
     * @param itemId the value for public.item_info.item_id
     *
     * @mbggenerated Fri Dec 04 14:21:06 JST 2015
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}