package sample.model;

public class TesttableKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.testtable.id
     *
     * @mbggenerated Mon Nov 30 20:46:23 JST 2015
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.testtable.id
     *
     * @return the value of public.testtable.id
     *
     * @mbggenerated Mon Nov 30 20:46:23 JST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.testtable.id
     *
     * @param id the value for public.testtable.id
     *
     * @mbggenerated Mon Nov 30 20:46:23 JST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}