package sample.model;

public class UserInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.user_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.user_id
     *
     * @return the value of public.user_info.user_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.user_id
     *
     * @param userId the value for public.user_info.user_id
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}