package sample.model;

public class UserInfo extends UserInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.password
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.name
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.gender
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.login_id
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    private String loginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_info.enabled
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.password
     *
     * @return the value of public.user_info.password
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.password
     *
     * @param password the value for public.user_info.password
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.name
     *
     * @return the value of public.user_info.name
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.name
     *
     * @param name the value for public.user_info.name
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.gender
     *
     * @return the value of public.user_info.gender
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.gender
     *
     * @param gender the value for public.user_info.gender
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.login_id
     *
     * @return the value of public.user_info.login_id
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public String getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.login_id
     *
     * @param loginId the value for public.user_info.login_id
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public void setLoginId(String loginId) {
        this.loginId = loginId == "nullだよ～ん" ? null : loginId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_info.enabled
     *
     * @return the value of public.user_info.enabled
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_info.enabled
     *
     * @param enabled the value for public.user_info.enabled
     *
     * @mbggenerated Tue Dec 01 21:08:33 JST 2015
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}