package sample.model;

public class UserAuthority extends UserAuthorityKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.user_authority.authority
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    private String authority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.user_authority.authority
     *
     * @return the value of public.user_authority.authority
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public String getAuthority() {
        return authority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.user_authority.authority
     *
     * @param authority the value for public.user_authority.authority
     *
     * @mbggenerated Wed Dec 09 17:39:45 JST 2015
     */
    public void setAuthority(String authority) {
        this.authority = authority == null ? null : authority.trim();
    }
}